$urls = @(
    "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg",
    "https://upload.wikimedia.org/wikipedia/commons/4/42/Flag_of_the_British_Virgin_Islands.svg",
    "https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg",
    "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg",
    "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg",
    "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg",
    "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Montserrat.svg",
    "https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg",
    "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg",
    "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg",
    "https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg",
    "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg",
    "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Anguilla.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_the_Cayman_Islands.svg",
    "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag-of-Martinique.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_Cura%C3%A7ao.svg",
    "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg",
    "https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg",
    "https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Puerto_Rico.svg",
    "https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg",
    "https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_the_United_States_Virgin_Islands.svg",
    "https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Guadeloupe_%28UPLG%29.svg",
    "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Aruba.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Sint_Eustatius.svg",
    "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_Saint_Martin_island_%28Unification_flag%29.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Saint_Barth%C3%A9lemy_%28local%29.svg",
    "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Sint_Maarten.svg",
    "https://upload.wikimedia.org/wikipedia/commons/1/1e/Flag_of_Bonaire.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Anguilla.svg",
    "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg",
    "https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg",
    "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg",
    "https://upload.wikimedia.org/wikipedia/commons/4/42/Flag_of_the_British_Virgin_Islands.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_the_Cayman_Islands.svg",
    "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg",
    "https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg",
    "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg",
    "https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Guadeloupe_%28UPLG%29.svg",
    "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg",
    "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag-of-Martinique.svg",
    "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Montserrat.svg",
    "https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Puerto_Rico.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Saint_Barth%C3%A9lemy_%28local%29.svg",
    "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_Saint_Martin_island_%28Unification_flag%29.svg",
    "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg",
    "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg",
    "https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg",
    "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Sint_Maarten.svg",
    "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg",
    "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg",
    "https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg",
    "https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_the_United_States_Virgin_Islands.svg",
    "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Aruba.svg",
    "https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_Cura%C3%A7ao.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg",
    "https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg",
    "https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Sint_Eustatius.svg",
    "https://upload.wikimedia.org/wikipedia/commons/5/5a/Flag_of_Saba.svg",
    "https://upload.wikimedia.org/wikipedia/commons/1/1e/Flag_of_Bonaire.svg"
) | Select-Object -Unique

foreach ($url in $urls) {
    $fileName = [System.IO.Path]::GetFileName([System.Uri]::UnescapeDataString($url))
    Invoke-WebRequest -Uri $url -OutFile $fileName -UserAgent "Mozilla/5.0"
    
    # Pause for 10 second between downloads
    Start-Sleep -Seconds 10
}